import numpy

In [2]:
import numpy as np
#numpy adalah library kalo np itu variabelnya bebas diganti sesuka hati

ilustrasi perbedaan pakai list dengan numpy

In [3]:
"""array biasa"""
x = [1,2,5]
"""pakai numpy"""
x = np.array([1, 2, 3])
#memanggil np dan array


Operasi Matematika Array

In [4]:
a = [5, 5, 7]
b = [ 7,8,9]
print("Pakai biasa")
c = [x + y for x, y in zip(a, b)]
print(c)
print()

print("Pakai numpy")
a = np.array([1, 2, 3]) + ([4, 5, 6])
print(a)
print(a.tolist()) 
# .tolist agar bisa diberikan koma setiap value tmpt yang beda

Pakai biasa
[12, 13, 16]

Pakai numpy
[5 7 9]
[5, 7, 9]


penggabungan array atau tambah elemen dengan +

In [5]:
x = [1, 2, 3, 4]
y = [5, 6, 7, 8]
z = x + y
print(z)

[1, 2, 3, 4, 5, 6, 7, 8]


penambahan elemen

In [6]:
"""dengan list (biasa)"""
xlist = [1, 2, 3, 4]
print("Kondisi awal array x :", xlist)
xlist.extend([5,6,7,8])
xlist.append(9) #append hanya menerima satu inputan saja
print("Kondisi akhir array x :", xlist)

"""dengan numpy"""
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
z = np.concatenate((x, y))
print(z)

Kondisi awal array x : [1, 2, 3, 4]
Kondisi akhir array x : [1, 2, 3, 4, 5, 6, 7, 8, 9]
[1 2 3 4 5 6 7 8]


fungsi ndim : menghitung jumlah array
fungsi shape : menghitung jumlah baris dan kolom
fungsi size : menghitung jumlah seluruh elemen
fungsi dtype : mengetahui tipe data yang digunakan


In [7]:
x2d = np.array([[1, 2, 3], [4, 5, 6]])

x3d = np.array([[[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17,
18]]])
x4d = np.array([[[[1], [2]], [[3], [4]]], [[[5], [6]], [[7], [8]]]])
print("Dimensi array x:", x2d.ndim)
print("Dimensi array x:", x3d.ndim)
print("Dimensi array x:", x4d.ndim)
"""cara menghitung array itu dimulai dari angka (value)
hingga -1 siku"""
print("Shape x2d:", x2d.shape)
print("Shape x3d:", x3d.shape)
print("Shape x4d:", x4d.shape)
"""
penjelasan
[[1], [2]] -> 2 balok utamaa
1], [2 -> 2 matriks
[1], [2] -> setiap matriks berisi 2 baris dan 1 angka

"""
#size
print("size x2d:", x2d.size)
print("size x3d:", x3d.size)
print("size x4d:", x4d.size)
x2 = np.array([5.7])
x3 = np.array([5])
print("tipe data x2 = ", x2.dtype)
print("tipe data x3 = ", x3.dtype)
"""
misal kalo hasilnya (2, 2, 2, 1) artinya
ada 2 balok utama, setiap balok berisi 2 matriks, setiap matriks berisi 2 baris, dan setiap baris memiliki 1 angka
"""

Dimensi array x: 2
Dimensi array x: 3
Dimensi array x: 4
Shape x2d: (2, 3)
Shape x3d: (2, 2, 3)
Shape x4d: (2, 2, 2, 1)
size x2d: 6
size x3d: 12
size x4d: 8
tipe data x2 =  float64
tipe data x3 =  int64


'\nmisal kalo hasilnya (2, 2, 2, 1) artinya\nada 2 balok utama, setiap balok berisi 2 matriks, setiap matriks berisi 2 baris, dan setiap baris memiliki 1 angka\n'

Deklarasi Array dengan NumPy


In [8]:
x = np.zeros((2, 3))
print(x)
# membuat array dengan bentuk 2 baris 3 kolom
# tapi mengisi semua elemen dengan nilai nol
x = np.ones((3, 4))
print(x) 
# membuat array dengan bentuk 2 baris 3 kolom
# tapi mengisi semua elemen dengan nilai 1
x = np.empty((2, 2))
print(x)
# membuat array dengan bentuk 2 baris 2 kolom
# tapi random karena tdk di inisialisasi
x = np.arange(0, 10, 2) # dari 0 hingga 10 dan setiap 2 angka loopnya
print(x)
#membuat urutan array mulai dari 0 hingga kurang dari 10 dengan
# interval 2 (interval tertentu)
x = np.linspace(0, 1, 5)
print(x)
#membuat array dengan 5 nilai yang terdistribusi secara 
#merata dari 0 hingga 1
x = np.full((2, 2), 7)
print(x)
#2 baris 2 kolom dengan angka 7
x = np.random.random((2, 3))
print(x)
#2 baris 3 kolom dengan angka acak
x = np.random.randint(0, 10, size=(3, 4))
print(x)
#acak nilai nya 0 sampai 10 tapi 3 baris 4 kolom
def penjumlahan(bilangan1, bilangan2):
    return bilangan1 + bilangan2
x = np.fromfunction(penjumlahan, (3, 3), dtype=int)
print(x)
#membuat array 3 baris 3 kolom tapi diurutkan
#dengan cara dimulai dari 0 hingga nilai max perbaris
#lalu lanjut dengan menghilangkan angka terkecil di baris sblmnya

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[7 7]
 [7 7]]
[[0.70025341 0.16828681 0.67544161]
 [0.9490998  0.53877113 0.01117848]]
[[0 6 1 3]
 [8 5 1 3]
 [0 5 6 0]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


Penambahan Elemen Array dari beberapa dimensi

In [9]:
"""tambah data tanpa dari var lain"""
#1D
a = np.array([1, 2, 3])
a = np.append(a, [4, 5]) # a lalu ditambahkan array pnmbhn
print("1D array setelah append:\n", a)
#2D
x = np.array([[1, 2], [3, 4]])
x = np.append(x, [[5, 6]], axis=0) # x lalu ditambahkan array pnmbhn
print("2D array setelah append:\n", x)

"""tambah data dari var lain pakai concacenate"""
#1D
a = np.array([1, 2])
b = np.array([3, 4])
c = np.concatenate((a, b))
print("1D array setelah concatenate:\n", c)
#2D
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
z = np.concatenate((x, y), axis=0)
print("2D array setelah concatenate:\n", z)

"""pakai insert, berguna ingin menambahkan
    data tetapi tata letak sesuai keinginan"""
#1D
a = np.array([1, 2, 3])
a = np.insert(a, 1, 4) # Insert '4' pada index 1
print("1D array setelah insert:\n", a)
#2D
x = np.array([[1, 2], [3, 4]])
x = np.insert(x, 0, [5, 6], axis=0) # Insert baris [5, 6] index 0
print("2D array setelah insert:\n", x)

"""tambah data dari var lain pakai npstack
    walau cara kerjanya mirip dan fungsinya sama
"""
# stack pada array 1D
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.stack((a, b))
print("1D array setelah stack:\n", c)
print("Shape dari array c:", c.shape)
# stack pada array 2D
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
z = np.stack((x, y))
print("2D array setelah stack:\n", z)
print("Shape dari array z:", z.shape)

1D array setelah append:
 [1 2 3 4 5]
2D array setelah append:
 [[1 2]
 [3 4]
 [5 6]]
1D array setelah concatenate:
 [1 2 3 4]
2D array setelah concatenate:
 [[1 2]
 [3 4]
 [5 6]]
1D array setelah insert:
 [1 4 2 3]
2D array setelah insert:
 [[5 6]
 [1 2]
 [3 4]]
1D array setelah stack:
 [[1 2 3]
 [4 5 6]]
Shape dari array c: (2, 3)
2D array setelah stack:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape dari array z: (2, 2, 2)


penghapusan elemen array

In [10]:
"""`np.delete()` untuk menghapus elemen pada array 1D"""
x = np.array([1, 2, 3, 4, 5])

x = np.delete(x, 3)# x = nama variabel array, 3 = hapus index ke 3
print(x)

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x = np.delete(x, 1, axis=1)  # hapus kolom indeks 1 (kolom kekedua)
print(x)
x = np.delete(x, 1, axis=0) # hapus indeks 1 (baris kedua)
print(x)

x = np.array([1, 2, 3, 4, 5])

x = np.where(x > 3, np.nan, x)
#ketika dimana x lebih besar dari 3
# Mengganti elemen yang lebih besar dari 3 dengan nan
x = x[~np.isnan(x)]
# Menghapus elemen NaN dari array (fungsi insannya)
print(x)


x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
hasil = np.delete(x,5)

#hasil = hasil.reshape(3,-1)
"""akan menghasilkan error jadi tidak bisa hapus 1 value dalam
    array, mau tidak mau kalo hapus 1 value jadi array 1d"""
print(hasil)

[1 2 3 5]
[[1 3]
 [4 6]
 [7 9]]
[[1 3]
 [7 9]]
[1. 2. 3.]
[1 2 3 4 5 7 8 9]


mengurutkan array

In [11]:
#1. pakai np.sort()
x = np.array([3, 1, 2])
y = np.sort(x) #panggil fungsi sort
print("Array yang telah diurutkan:", y)

#2. array.sort()
x = np.array([3, 1, 2])
x.sort() # elemen array diurutkan secara langsung di dalam array asli
print("Array yang telah diurutkan:", x)

#3. np.sort() utk lebih dri 1d
x = np.array([[3, 1, 2], [9, 7, 8]])
y = np.sort(x, axis=0) # Mengurutkan sepanjang kolom dahulu
print("Array yang telah diurutkan sepanjang kolom:\n", y)
z = np.sort(x) # baru Mengurutkan sepanjang baris
print("Array yang telah diurutkan sepanjang baris:\n", z)

Array yang telah diurutkan: [1 2 3]
Array yang telah diurutkan: [1 2 3]
Array yang telah diurutkan sepanjang kolom:
 [[3 1 2]
 [9 7 8]]
Array yang telah diurutkan sepanjang baris:
 [[1 2 3]
 [7 8 9]]


Indexing dan Slicing Array

In [12]:
x = np.array([10, 20, 30, 40, 50])
print(x[2])
#cari val di index 2

x = np.array([10, 20, 30, 40, 50])
# Slicing untuk mendapatkan elemen dari indeks 1 sampai 3
subset = x[1:4]
print(subset)
#cari val di index 1 hgg 4

x = np.array([10, 20, 30, 40, 50])
# Boolean mask untuk memilih elemen yang lebih besar dari 25
mask = x > 25
print("Hasil boolean dari masking:", mask)
subset = x[mask]
print("Hasil elemen:", subset)
#print 1 menhgasilkan boolean jk lbh 25 maka true
#print 2 plh elemen lbh 25


x = np.array([10, 20, 30, 40, 50])
# Array indeks
indeks = [1, 3]
subset = x[indeks]
print(subset)
#hasilkan val di index 1 dn 3 pada 1 dimensi

"""2d"""
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
element = x[1, 2]
print(element)
# Mengakses elemen pada baris ke-2 (index 1) dan kolom ke-3 (index 2)
element = x[2, 2]
print(element)
# Mengakses elemen pada baris ke-3 (index 2) dan kolom ke-3 (index 2)

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
subset = x[1, ...]
print(subset)
# Mengakses semua elemen pada baris ke-1

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Indeks baris dan kolom
rows = [0, 2] #baris 1 dan 3 (index 0 dan 2)
cols = [1, 2] #ambil kolom index 1 dan 2 (kolom 2 dan 3)
subset = x[np.ix_(rows, cols)]
print(subset)


30
[20 30 40]
Hasil boolean dari masking: [False False  True  True  True]
Hasil elemen: [30 40 50]
[20 40]
6
9
[4 5 6]
[[2 3]
 [8 9]]


Penyalinan (Copy) Array

In [13]:
#shallow copy atau view()
#tidak membuat copy seperti hard yang beda memori dan maka dari itu
#karena dia refrence bukan salin individu jadi refrence pada
#memori yang sama
x = np.array([1, 2, 3, 4, 5])
# Membuat shallow copy menggunakan view()
y = x.view()
# Mengubah elemen pertama dari shallow copy
y[0] = 99
print("Array asli:", x)
print("Shallow copy:", y)

#Copy, berbeda dengan shallow dia tidak refrence
x = np.array([1, 2, 3, 4, 5])
# Membuat deep copy menggunakan copy()
y = x.copy()
# Mengubah elemen pertama dari deep copy
y[0] = 99
print("Array asli:", x)
print("Deep copy:", y)


Array asli: [99  2  3  4  5]
Shallow copy: [99  2  3  4  5]
Array asli: [1 2 3 4 5]
Deep copy: [99  2  3  4  5]


Operasi Deep Array
mencari jumlah maksimum, minimum, sum, rata rata
maksimum = max
minimum = min
sum
rata rata = mean

In [14]:
x = np.array([1, 5, 3, 8, 2])
max_value = np.max(x)
print("Nilai maksimum:", max_value)

min_value = np.min(x)
print("Nilai minimum:", min_value)

sum_value = np.sum(x)
print("Jumlah total:", sum_value)

mean_value = np.mean(x)
print("Rata-rata:", mean_value)

Nilai maksimum: 8
Nilai minimum: 1
Jumlah total: 19
Rata-rata: 3.8


Transpose dan Reshape Array

In [15]:
"""fungsi transpose ini bisa digunakan untuk menampilkan
    satu baris dalam satu kolom"""
#transpose()
x = np.array([[1, 2, 3], [4, 5, 6]])
y = x.transpose()
print(y)
#np.transpose() sama aja fungsinya
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.transpose(x)
print(y)
#T` untuk transpose sama aja fungsinya
x = np.array([[1, 2, 3], [4, 5, 6]])
y = x.T
print(y)


""" Reshape
    -> mengubah bentuk array misal 2 dimensi bisa dijadikan
    3 dimensi atau 1 dimensi bisa dijadikan 3 dimensi dsb
"""
x = np.array([1, 2, 3, 4, 5, 6])
y = x.reshape((2, 3)) # 2baris 3 kolom
print(y)

#sama aja bedanya pake np doang
x = np.array([1, 2, 3, 4, 5, 6])
# Mengubah menjadi array 2D dengan 2 baris dan 3 kolom
y = np.reshape(x, (2, 3))
print(y)

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
